# Template service configuration for docker-compose.yaml
# Copy this section into the main docker-compose.yaml file

services:
  service-name:
    build:
      context: ../..  # Relative to docker/compose directory
      dockerfile: docker/service-name/Dockerfile
    image: ghcr.io/sv-afterglow/data-hub/service-name:latest
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Managed by update-service
    volumes:
      - ~/.data-hub:/data  # Persistent data
      - /etc/localtime:/etc/localtime:ro  # System time sync
    environment:
      - SERVICE_VAR1=default_value
      - SERVICE_VAR2=default_value
      - INFLUX_URL=http://influxdb:8086  # If using InfluxDB
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      - influxdb  # If using InfluxDB
    networks:
      - data-hub  # Internal network for service communication

# Note: The data-hub network is defined in the main docker-compose.yaml
# networks:
#   data-hub:
#     driver: bridge
