apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: server
    url: http://influxdb:8086
    database: signalk
    isDefault: true
    editable: true
    version: 1
    jsonData:
      httpMode: POST
