version: '3.8'

services:
  signalk:
    build:
      context: ../..  # Go up two levels from docker/compose
      dockerfile: docker/signalk/Dockerfile
    image: ghcr.io/sv-afterglow/data-hub/signalk:latest
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Managed by update-service
    network_mode: host  # Required for NMEA2000
    volumes:
      - ~/.data-hub/config/signalk:/home/node/.signalk
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - influxdb

  influxdb:
    build:
      context: ../..
      dockerfile: docker/influxdb/Dockerfile
    image: ghcr.io/sv-afterglow/data-hub/influxdb:latest
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Managed by update-service
    ports:
      - "8086:8086"
    volumes:
      - ~/.data-hub/config/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=signalk
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    networks:
      - data-hub

  grafana:
    build:
      context: ../..
      dockerfile: docker/grafana/Dockerfile
    image: ghcr.io/sv-afterglow/data-hub/grafana:latest
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Managed by update-service
    ports:
      - "3001:3000"
    volumes:
      - ~/.data-hub/config/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    networks:
      - data-hub

  system_metrics:
    build:
      context: ../..
      dockerfile: docker/system_metrics/Dockerfile
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Managed by update-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/class/thermal:/sys/class/thermal:ro
      - ~/.data-hub:/data  # Data hub root directory
      - ~/.data-hub/config/system_metrics:/config  # Service config
    environment:
      - INFLUX_URL=http://influxdb:8086
      - COLLECTION_INTERVAL=10
    depends_on:
      - influxdb
    networks:
      - data-hub

  update_service:
    build:
      context: ../..
      dockerfile: docker/update_service/Dockerfile
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Managed by update-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc:/etc:ro
      - ~/.data-hub:/data
      - ../..:/app/repo  # Mount repo root for access to Dockerfiles
      - ~/.data-hub/config/update_service:/config  # Update service config
    environment:
      - INFLUX_URL=http://influxdb:8086
      - DATA_DIR=/data/state  # Set data dir to state directory
      - CONFIG_DIR=/config  # Update service config directory
    depends_on:
      - influxdb  # Ensure influxdb starts first
    working_dir: /app/repo  # Set working directory to repo root
    networks:
      - data-hub

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 3600 --label-enable
    networks:
      - data-hub
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  network_monitor:
    build:
      context: ../..  # Go up two levels from docker/compose
      dockerfile: docker/network_monitor/Dockerfile
    image: ghcr.io/sv-afterglow/data-hub/network_monitor:latest
    restart: always
    networks:
      - data-hub  # Use bridge network for service discovery
    privileged: true    # Required for WiFi monitoring
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Managed by update-service
    volumes:
      - /etc/localtime:/etc/localtime:ro  # System time sync
      - /sys/class/net:/sys/class/net:ro  # Network interface info
      - ~/.data-hub:/data                 # Data hub root directory
      - ~/.data-hub/config/network_monitor:/config  # Service config
    environment:
      - NETWORK_INTERFACE=wlan0
      - SPEED_TEST_INTERVAL=3600
      - WIFI_CHECK_INTERVAL=30
      - INFLUX_URL=http://influxdb:8086
      - MIN_SPEED_TEST_INTERVAL=600
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      - influxdb  # Requires InfluxDB for metrics storage
    cap_add:
      - NET_ADMIN  # Required for network interface access
      - NET_RAW    # Required for raw socket access

networks:
  data-hub:
    driver: bridge
