version: '3.8'

services:
  signalk:
    image: your-custom-signalk:latest 
    container_name: signalk
    network_mode: host
    volumes:
      - ./docker/signalk/config:/home/node/.signalk
    environment:
      - TZ=UTC
    restart: unless-stopped